Make Alpine image less hacky
Thanks to Stefan Wagner for some of this work

diff --git a/images/alpine/genimg b/images/alpine/genimg
--- a/images/alpine/genimg
+++ b/images/alpine/genimg
@@ -1,15 +1,69 @@
-#!/bin/sh -xe
-# This script should be run from a fresh Alpine installation
-# It will output root.img.qcow2, which is the sr.ht Alpine image
+#!/bin/sh -xeu
+echo "$release" >/dev/null # fail on -u if release unset
+
+cleanup() {
+	# The order here is important if you don't want to hose your mounts
+	umount -f /mnt/dev/pts 2>/dev/null || true
+	umount -f /mnt/dev/shm 2>/dev/null || true
+	umount -f /mnt/dev 2>/dev/null || true
+	umount -f /mnt/proc 2>/dev/null || true
+	umount -f /mnt/run 2>/dev/null || true
+	umount -f /mnt/sys 2>/dev/null || true
+	umount -f /mnt 2>/dev/null || true 
+	qemu-nbd --disconnect /dev/nbd0 || true
+}
 
 qemu-img create -f qcow2 root.img.qcow2 16G
-modprobe nbd
+modprobe nbd max_part=16
 qemu-nbd --connect=/dev/nbd0 root.img.qcow2
-trap 'qemu-nbd --disconnect /dev/nbd0' EXIT
+trap cleanup EXIT
 
-# Basic install
-setup-hostname -n build
-setup-interfaces -i <<EOF
+# Disk layout:
+# partition 1: boot (100M)
+# partition 2: swap (2G)
+# partition 3: root (remainder)
+dd if=/usr/share/syslinux/mbr.bin of=/dev/nbd0 bs=1 count=440
+sfdisk --no-reread /dev/nbd0 <<EOF
+1M,100M,L,*
+,2048M,S
+,,L
+EOF
+mdev -s
+
+mkfs.ext4 /dev/nbd0p1
+mkswap /dev/nbd0p2
+mkfs.ext4 /dev/nbd0p3
+
+mount /dev/nbd0p3 /mnt
+mkdir /mnt/boot
+mount /dev/nbd0p1 /mnt/boot
+swapon /dev/nbd0p2
+
+# TODO: Remove bash
+apk add -U -X http://dl-cdn.alpinelinux.org/alpine/$release/main/ \
+	--allow-untrusted \
+	--arch=x86_64 \
+	--root=/mnt \
+	--initdb \
+	acct alpine-base alpine-conf alpine-sdk linux-virt bash git openssh sudo \
+	syslinux
+
+mount --bind /dev /mnt/dev
+mount --bind /dev/pts /mnt/dev/pts
+mount --bind /dev/shm /mnt/dev/shm
+mount --bind /proc /mnt/proc
+mount --bind /run /mnt/run
+mount --bind /sys /mnt/sys
+
+run_root() {
+	local cmd="$@"
+	chroot /mnt /usr/bin/env \
+		PATH=/sbin:/usr/sbin:/bin:/usr/bin \
+		/bin/sh -c "$cmd"
+}
+
+run_root setup-hostname -n build
+run_root setup-interfaces -i <<EOF
 auto lo
 iface lo inet loopback
 
@@ -20,62 +74,48 @@ iface eth0 inet static
 	netmask 255.255.255.0
 	gateway 10.0.2.2
 EOF
-setup-dns -d example.org -n 1.1.1.1
-setup-timezone -z UTC
-setup-sshd -c openssh
-setup-ntp -c openntpd
-setup-apkrepos -f
+run_root setup-dns -d example.org -n 1.1.1.1
+run_root setup-timezone -z UTC
+run_root setup-apkrepos -f
 
-# Alpine copies our installed packages to the new disk
-# Note, this fucks shit up, only do this from bootstrap media
-cat >/etc/apk/world <<EOF
-acct
-alpine-base
-alpine-sdk
-bash
-git
-linux-pam
-linux-vanilla
-openssh
-shadow
-syslinux
-EOF
+extlinux --install /mnt/boot
 
-sed -i /sbin/setup-disk -e 's/die "$i is not a suitable for partitioning"/true/'
+run_root rc-update add ntpd default
+run_root rc-update add sshd default
+run_root rc-update add crond default
+for i in hwclock modules sysctl hostname bootmisc networking syslog swap urandom
+do
+	run_root rc-update add $i boot
+done
+for i in mount-ro killprocs savecache
+do
+	run_root rc-update add $i shutdown
+done
 
-ERASE_DISKS=/dev/nbd0 setup-disk -m sys /dev/nbd0
+sed -e 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' \
+	-i /mnt/etc/ssh/sshd_config
 
-# This gets lost during that process (TODO FIX)
-sudo apk add qemu-img
+run_root adduser -u 1000 -D -h /home/build -s /bin/sh build
+run_root adduser build wheel
+run_root adduser build kvm
+run_root adduser build abuild
+run_root passwd -u build
 
-# Extra sr.ht changes
-mount /dev/nbd0p3 /mnt
-sed -e 's/#PermitEmptyPasswords no/PermitEmptyPasswords yes/' -i /mnt/etc/ssh/sshd_config
-
-echo -- "build:x:1000:1000::/home/build:/bin/ash" >> /mnt/etc/passwd
-cat >>/mnt/etc/group <<EOF
-build:!:1000:
-sudo:x:1001:build
-EOF
-sed -i /mnt/etc/group -e 's/^kvm.*/kvm:x:34:kvm,build/'
-echo -- "build::17742::::::" >>/mnt/etc/shadow
-echo '%sudo ALL=(ALL) NOPASSWD: ALL' >> /mnt/etc/sudoers
-
-mkdir -p /mnt/home/build
-chown 1000:1000 /mnt/home/build
-
+printf '%s\n' "%wheel ALL=(ALL) NOPASSWD: ALL" >> /mnt/etc/sudoers
 rm -f /mnt/etc/motd
 
-umount /mnt
-
-mount /dev/nbd0p1 /mnt
-
-cat >/mnt/extlinux.conf <<EOF
+cat >/mnt/boot/extlinux.conf <<EOF
 DEFAULT vanilla
 LABEL vanilla
-	LINUX vmlinuz-vanilla
-	INITRD initramfs-vanilla
+	LINUX vmlinuz-virt
+	INITRD initramfs-virt
 	APPEND root=/dev/vda3 rw modules=sd-mod,usb-storage,ext4 quiet rootfstype=ext4
 EOF
 
-umount /mnt
+cat >>/mnt/etc/fstab <<EOF
+/dev/vda1 /boot ext4 rw,relatime,data=ordered 0 0
+/dev/vda2 swap swap defaults 0 0
+/dev/vda3 / ext4 rw,relatime,data=ordered 0 0
+EOF
+
+sync
